clear all
close all
clc

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\David\Nextcloud\CCSU\Research\output.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/02/07 18:32:16

%% Initialize variables.
filename = 'C:\Users\David\Nextcloud\CCSU\Research\output.txt';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
t = dataArray{:, 1};
Ax = dataArray{:, 2};
Ay = dataArray{:, 3};
Az = dataArray{:, 4};
p = dataArray{:, 5};
q = dataArray{:, 6};
r = dataArray{:, 7};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

dataIMU=[t,Ax,Ay,-Az,p,q,r];
initial=zeros(3);
out=find_position(dataIMU,initial);
